version: 2
jobs:
  centos6:
    steps:
      - checkout
      - run:
         name: centos6 build
         command: |
           docker pull centos:6
           make centos6
  centos7:
    steps:
      - checkout
      - run:
         name: centos7 build
         command: |
           docker pull centos:7
           make centos7

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - centos6
      - centos7
