
build-settings: &build-settings
  machine: true

jobs:
  centos5:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - centosbuild-5-assets-
      - checkout
      - run:
         name: centos5 build
         command: |
           docker load -i ~/docker/centosbuild-5.tar > /dev/null 2>&1 || true
           docker pull centos:5
           make centos5
           mkdir -p ~/docker
           docker save -o ~/docker/centosbuild-5.tar dockbuild/centos5:latest
      - run:
         name: centos5 test
         command: |
           make centos5.test
      - save_cache:
          key: centosbuild-5-assets-{{ .Revision }}
          paths: ~/docker/centosbuild-5.tar
  centos6:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - centosbuild-6-assets-
      - checkout
      - run:
         name: centos6 build
         command: |
           docker load -i ~/docker/centosbuild-6.tar > /dev/null 2>&1 || true
           docker pull centos:6
           make centos6
           mkdir -p ~/docker
           docker save -o ~/docker/centosbuild-6.tar dockbuild/centos6:latest
      - run:
         name: centos6 test
         command: |
           make centos6.test
      - save_cache:
          key: centosbuild-6-assets-{{ .Revision }}
          paths: ~/docker/centosbuild-6.tar
  centos7:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - centosbuild-7-assets-
      - checkout
      - run:
         name: centos7 build
         command: |
           docker load -i ~/docker/centosbuild-7.tar > /dev/null 2>&1 || true
           docker pull centos:7
           make centos7
           mkdir -p ~/docker
           docker save -o ~/docker/centosbuild-7.tar dockbuild/centos7:latest
      - run:
         name: centos7 test
         command: |
           make centos7.test
      - save_cache:
          key: centosbuild-7-assets-{{ .Revision }}
          paths: ~/docker/centosbuild-7.tar
  ubuntu1004:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - ubuntu1004-assets-
      - checkout
      - run:
         name: ubuntu1004 build
         command: |
           docker load -i ~/docker/ubuntu1004.tar > /dev/null 2>&1 || true
           docker pull ubuntu:16.04
           make ubuntu1004
           mkdir -p ~/docker
           docker save -o ~/docker/ubuntu1004.tar dockbuild/ubuntu1004:latest
      - run:
         name: ubuntu1004 test
         command: |
           make ubuntu1004.test
      - save_cache:
          key: ubuntu1004-assets-{{ .Revision }}
          paths: ~/docker/ubuntu1004.tar
  ubuntu1604:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - ubuntu1604-assets-
      - checkout
      - run:
         name: ubuntu1604 build
         command: |
           docker load -i ~/docker/ubuntu1604.tar > /dev/null 2>&1 || true
           docker pull ubuntu:16.04
           make ubuntu1604
           mkdir -p ~/docker
           docker save -o ~/docker/ubuntu1604.tar dockbuild/ubuntu1604:latest
      - run:
         name: ubuntu1604 test
         command: |
           make ubuntu1604.test
      - save_cache:
          key: ubuntu1604-assets-{{ .Revision }}
          paths: ~/docker/ubuntu1604.tar
  ubuntu1804:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - ubuntu1804-assets-
      - checkout
      - run:
         name: ubuntu1804 build
         command: |
           docker load -i ~/docker/ubuntu1804.tar > /dev/null 2>&1 || true
           docker pull ubuntu:18.04
           make ubuntu1804
           mkdir -p ~/docker
           docker save -o ~/docker/ubuntu1804.tar dockbuild/ubuntu1804:latest
      - run:
         name: ubuntu1804 test
         command: |
           make ubuntu1804.test
      - save_cache:
          key: ubuntu1804-assets-{{ .Revision }}
          paths: ~/docker/ubuntu1804.tar
  deploy:
    <<: *build-settings
    steps:
      - restore_cache:
          key: centosbuild-5-assets-{{ .Revision }}
      - deploy:
          name: Deploy centos5
          command: |
            docker load -i ~/docker/centosbuild-5.tar
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push dockbuild/centos5:latest
            fi
      - restore_cache:
          key: centosbuild-6-assets-{{ .Revision }}
      - deploy:
          name: Deploy centos6
          command: |
            docker load -i ~/docker/centosbuild-6.tar
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push dockbuild/centos6:latest
            fi
      - restore_cache:
          key: centosbuild-7-assets-{{ .Revision }}
      - deploy:
          name: Deploy centos7
          command: |
            docker load -i ~/docker/centosbuild-7.tar
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push dockbuild/centos7:latest
            fi
      - restore_cache:
          key: ubuntu1004-assets-{{ .Revision }}
      - deploy:
          name: Deploy ubuntu1004
          command: |
            docker load -i ~/docker/ubuntu1004.tar
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push dockbuild/ubuntu1004:latest
            fi
      - restore_cache:
          key: ubuntu1604-assets-{{ .Revision }}
      - deploy:
          name: Deploy ubuntu1604
          command: |
            docker load -i ~/docker/ubuntu1604.tar
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push dockbuild/ubuntu1604:latest
            fi
      - restore_cache:
          key: ubuntu1804-assets-{{ .Revision }}
      - deploy:
          name: Deploy ubuntu1804
          command: |
            docker load -i ~/docker/ubuntu1804.tar
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push dockbuild/ubuntu1804:latest
            fi
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - centos5
      - centos6
      - centos7
      - ubuntu1004
      - ubuntu1604
      - ubuntu1804
      - deploy:
          requires:
            - centos5
            - centos6
            - centos7
            - ubuntu1004
            - ubuntu1604
            - ubuntu1804
