version: 2
jobs:
  centos5:
    steps:
      - checkout
      - run:
         name: centos5 build
         command: |
           docker pull centos:5
           make centos5
  centos6:
    steps:
      - checkout
      - run:
         name: centos6 build
         command: |
           docker pull centos:6
           make centos5

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - centos5
      - centos6
